import Link from "next/link";
import BackOfficeError from "./components/backoffice-error";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NotFound() {
  // Check the path to determine which layout to use
  return <BackOfficeError statusCode={404} />;
  return (
    <div>
      <h2>Not Found</h2>
      <p>Could not find requested resource</p>
      <Link href="/">Return Home</Link>
    </div>
  );
}
